Adds ReadTypes workload for mlmd_bench.
BrianSong/ml-metadata pull request #13
Opened 2020-08-11 15:51 UTC by BrianSong

2020-08-11 17:56 UTC, hughmiao requested changes

2020-08-11 17:56 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/util.cc
> +    case ReadTypesConfig::ARTIFACT_TYPE_BY_NAME:
take a look [1]

[1] https://google.github.io/styleguide/cppguide.html#Loops_and_Switch_Statements

2020-08-11 17:56 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/util_test.cc
> +
vector<xx> a = {::ALL_ARTIFACT_TYPES, ... }
vector<int> size?

for (spec : a ) {
    read_types_configs ..
    GetExistingTypes
    EXPECT_THAT
}

2020-08-11 17:56 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +      break;
drop

2020-08-11 17:56 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +      TF_RETURN_IF_ERROR(GetTransferredBytes<ArtifactType>(
return

2020-08-11 17:56 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +        TF_RETURN_IF_ERROR(GetTransferredBytes<ArtifactType>(
return

2020-08-11 18:47 UTC, BrianSong commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +        TF_RETURN_IF_ERROR(GetTransferredBytes<ArtifactType>(
Since here, it is inside a for loop, I still keep the TF_RETURN_IF_ERROR()

2020-08-14 16:01 UTC, hughmiao approved these changes
overall LGTM, please fix before commit.

2020-08-14 16:01 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/util_test.cc
> +  std::vector<ReadTypesConfig::Specification> specification{
use a pair

2020-08-14 16:01 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/benchmark.cc
> +    }
sync to the head return

2020-08-14 16:01 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +      GetArtifactTypesRequest request = absl::get<GetArtifactTypesRequest>(
auto

2020-08-14 16:01 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +      return GetTransferredBytes<ArtifactType>(
nit drop first <ArtifactType>, ditto elsewhere

2020-08-14 16:01 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +      return tensorflow::errors::Unimplemented(
InvalidArgument

2020-08-14 16:01 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +}
inline

2020-08-14 16:01 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +      InitializeReadRequest<GetArtifactTypesRequest>(request);
request = GetArtifactTypesRequest()

2020-08-14 16:01 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload.cc
> +  curr_bytes += 8;
use a constant.

2020-08-14 16:01 UTC, hughmiao commented on ml_metadata/tools/mlmd_bench/read_types_workload_test.cc
> +
use a for of {ReadTypesConfig::ALL_ARTIFACT_TYPES ... }

2020-08-14 19:43 UTC, merged